_target_: torch.utils.data.DataLoader
dataset:
  _target_: dataset.CIFAR_ERAN
  data_path: ${oc.env:DATA_DIR}/cifar10
  train: false
  flatten: false
  no_points: 1000
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2023, 0.1994, 0.201]
batch_size: 1